In [1]:
import numpy as np

In [2]:
S = np.array([1.0, 2.0, -1.0])

In [5]:
def naive_softmax(S_input: np.ndarray) -> np.ndarray:
  return np.exp(S_input) / np.sum(np.exp(S_input))

In [6]:
naive_softmax(S)

array([0.25949646, 0.70538451, 0.03511903])

In [7]:
np.sum(naive_softmax(S))

1.0

In [8]:
S_extreme = np.array([450.0, 2.0, -1.0])

In [9]:
naive_softmax(S_extreme)

array([1.00000000e+000, 2.72943092e-195, 1.35890364e-196])

In [10]:
S_really_extreme = np.array([4500.0, 2.0, -1.0])

In [11]:
naive_softmax(S_really_extreme)

<ipython-input-5-1fe0af2394a7>:2: RuntimeWarning: overflow encountered in exp
  return np.exp(S_input) / np.sum(np.exp(S_input))
<ipython-input-5-1fe0af2394a7>:2: RuntimeWarning: invalid value encountered in divide
  return np.exp(S_input) / np.sum(np.exp(S_input))


array([nan,  0.,  0.])

In [12]:
def softmax_with_trick(S_input: np.ndarray) -> np.ndarray:
  max_s = np.max(S_input)
  negative_or_null_S = S_input - max_s
  exp_S = np.exp(negative_or_null_S)
  return exp_S / np.sum(exp_S)

In [13]:
softmax_with_trick(S)

array([0.25949646, 0.70538451, 0.03511903])

In [14]:
softmax_with_trick(S_extreme)

array([1.00000000e+000, 2.72943092e-195, 1.35890364e-196])

In [15]:
softmax_with_trick(S_really_extreme)

array([1., 0., 0.])